export const STRINGS = {
  game: {
    title: "Sparkle",
    initialMessage: "Roll the dice to start!",
    newGameStarted: "New game started! Roll the dice!",
    selectAndBank: "Select scoring dice and bank them, or roll again!",
    bankedPoints: (score: number) =>
      `Banked ${score} points! Roll again or end turn.`,
    hotDice: (score: number, count: number) =>
      `Banked ${score} points! Hot dice! Rolling all ${count} dice again...`,
    turnOver: (score: number) => `Turn over! You scored ${score} points!`,
    rerollsRemaining: (count: number) =>
      `Re-rolled! ${count} re-roll(s) remaining.`,
    sparkleNoScore: "✨ SPARKLE! No scoring dice! Use a re-roll if available.",
    sparkleStillSparkled: (count: number) =>
      `✨ SPARKLE! Still sparkled! Use a re-roll if available (${count} Extra Dice left).`,
    gameOver: (score: number) => `✨ SPARKLE! Game Over! Final score: ${score}`,
    sparkleContinue: (score: number) =>
      `✨ SPARKLE! Lost turn points, but you can continue! Total: ${score}`,
    autoRerollSaved: "🔄 Auto Re-roll used! Saved!",
    autoRerollFailed: "🔄 Auto Re-roll used! Still sparkled! ✨",
    upgradeApplied: "Upgrade applied!",
    bonusRerollAdded: "Bonus re-roll added!",
    guhkleTriggered: "😲 GUHKLE! First roll sparkle! Auto re-rolling...",
    guhkleSaved: "😅 GUHKLE! Scored on re-roll!",
    guhkleFailed: "💀 DOUBLE GUHKLE! Still sparkled!",
  },
  errors: {
    selectDice: "Select some dice first!",
    notScoring: "Selected dice do not score!",
    bankFirst: "Bank your selected dice first!",
    mustBank: "You must bank some points before ending your turn!",
    thresholdNotMet: (threshold: number, current: number) =>
      `Need total score of ${threshold} to end turn. You have ${current}. Keep rolling!`,
    noRerolls: "No re-rolls available!",
    noExtraDice: "No extra dice available!",
    boardFull: "Board is already full!",
  },
  rules: {
    header: "Sparkle Rules",
    scoringHeader: "Scoring Rules",
    shortcutsHeader: "Keyboard Shortcuts",
    one: "1",
    five: "5",
    threeOfKind: "Three of a kind",
    threeOfKindScore: "1000 (111) or value×100",
    fourOfKind: "4444",
    fiveOfKind: "55555",
    sixOfKind: "666666",
    straight: "123456",
    threePairs: "112233",
  },
  ui: {
    turn: "Turn",
    nextLevel: (turn: number) => `Next Level: Turn ${turn}`,
    rerolls: "Re-Rolls",
    extraDice: "Extra Dice",
    highScore: "High Score",
    limit: "Limit",
    nextLimit: (score: number) => `Next Limit: ${score}`,
    totalScore: "Total",
    bankedScore: "Banked",
    stagedScore: "Staged",
    rules: "Rules",
    backToGame: "Back to Game",
    playGame: "PLAY GAME",
    upgrades: "Upgrades",
    dieUpgrades: "Die Upgrades",
    chooseUpgrade: "Choose an Upgrade",
    position: (pos: number) => `Position ${pos}`,
    none: "None",
    roll: "Roll",
    rollTooltip: "Roll dice (Space)",
    reroll: "Re-Roll",
    rerollTooltip: "Re-roll unscored dice (R)",
    endTurn: "End Turn",
    endTurnTooltip: "End turn (Enter)",
    newGame: "New Game",
    newGameTooltip: "New game (Backspace)",
  },
  upgrades: {
    descriptions: {
      bankedMultiplier: "2x total turn score when this die is banked",
      bankedBonus: "+100 total turn score when this die is banked",
      autoReroll:
        "Automatically re-rolls this die if it causes a Sparkle (3 uses)",
      setBonus:
        "Increases score by N^3 where N is number of Set Bonus dice in the scoring set",
      extraDie: "Immediately gain +1 Extra Die",
    },
    labels: {
      bankedMultiplier: "2x Banked",
      bankedBonus: "+100 Banked",
      autoReroll: "Auto Reroll",
      setBonus: "Set Bonus",
      extraDie: "Extra Die",
    },
  },
};
