export const STRINGS = {
  game: {
    title: "Sparkle",
    initialMessage: "Roll the dice to start!",
    newGameStarted: "New game started! Roll the dice!",
    selectAndBank: "Select scoring dice and bank them, or roll again!",
    bankedPoints: (score: number) => `Banked ${score} points! Roll again or end turn.`,
    hotDice: (score: number, count: number) => `Banked ${score} points! Hot dice! Rolling all ${count} dice again...`,
    turnOver: (score: number) => `Turn over! You scored ${score} points!`,
    rerollsRemaining: (count: number) => `Re-rolled! ${count} re-roll(s) remaining.`,
    sparkleNoScore: "💥 SPARKLE! No scoring dice! Discard unscored or use a re-roll.",
    sparkleStillSparkled: (count: number) => `💥 SPARKLE! Still sparkled! Discard unscored or re-roll if available (${count} left).`,
    gameOver: (score: number) => `✨ SPARKLE! Game Over! Final score: ${score}`,
    sparkleContinue: (score: number) => `✨ SPARKLE! Lost turn points, but you can continue! Total: ${score}`,
    autoRerollSaved: "🔄 Auto Re-roll used! Saved!",
    autoRerollFailed: "🔄 Auto Re-roll used! Still sparkled! 💥",
    discardSuccess: "Discarded all unscored dice. Re-rolling banked dice!",
    addDieHelp: "Added a die! It might help.",
    addDieSparkle: "Added a die, but still no score!",
    upgradeApplied: "Upgrade applied!",
    bonusRerollAdded: "Bonus re-roll added!",
  },
  errors: {
    selectDice: "Select some dice first!",
    notScoring: "Selected dice do not score!",
    bankFirst: "Bank your selected dice first!",
    mustBank: "You must bank some points before ending your turn!",
    thresholdNotMet: (threshold: number, current: number) => `Need total score of ${threshold} to end turn. You have ${current}. Keep rolling!`,
    noRerolls: "No re-rolls available!",
    noExtraDice: "No extra dice available!",
    boardFull: "Board is already full!",
    onlyDiscardAfterSparkle: "You can only discard dice after a sparkle!",
  },
  rules: {
    header: "Sparkle Rules",
    scoringHeader: "Scoring Rules",
    shortcutsHeader: "Keyboard Shortcuts",
    one: "1",
    five: "5",
    threeOfKind: "Three of a kind",
    threeOfKindScore: "1000 (111) or value×100",
    fourOfKind: "XXXX",
    fiveOfKind: "XXXXX",
    sixOfKind: "XXXXXX",
    straight: "1-2-3-4-5-6",
    threePairs: "XXYYZZ",
  },
  ui: {
    turn: "Turn",
    nextLevel: (turn: number) => `Next Level: Turn ${turn}`,
    rerolls: "Re-Rolls",
    extraDice: "Extra Dice",
    highScore: "High Score",
    limit: "Limit",
    nextLimit: (score: number) => `Next Limit: ${score}`,
    totalScore: "Total Score",
    bankedScore: "Banked Score",
    stagedScore: "Staged Score",
    rules: "Rules",
    backToGame: "Back to Game",
    playGame: "PLAY GAME",
    upgrades: "Upgrades",
    dieUpgrades: "Die Upgrades",
    chooseUpgrade: "Choose an Upgrade",
    position: (pos: number) => `Position ${pos}`,
    none: "None",
    roll: "Roll",
    rollTooltip: "Roll dice (Space)",
    reroll: "Re-Roll",
    rerollTooltip: "Re-roll last roll (R)",
    discard: "Discard All",
    discardTooltip: "Discard all unscored dice (D)",
    extraDie: (count: number) => `+ Die (${count})`,
    extraDieTooltip: "Add an extra die to the board",
    endTurn: "End Turn",
    endTurnTooltip: "End turn (Enter)",
    newGame: "New Game",
    newGameTooltip: "New game (Backspace)",
  },
  upgrades: {
    scoreMultiplier: "2x score multiplier when this die is scored",
    scoreBonus: "100+ score bonus when this die is scored",
    bankedMultiplier: "2x banked score multiplier when this die is banked",
    bankedBonus: "100+ banked score bonus when this die is banked",
    autoReroll: "3x Auto re-roll on sparkle (if this die is rolled)",
    tenXMultiplier: "3x 10x multiplier when this die is scored",
    setBonus: "2x multiplier for each die in a set with this upgrade",
    upgradeChoice: "Every 5 turns, you get to choose an upgrade...",
  }
};
