export const STRINGS = {
  game: {
    title: "Sparkle",
    initialMessage: "Roll the dice to start!",
    newGameStarted: "New game started! Roll the dice!",
    selectAndBank: "Select scoring dice and bank them, or roll again!",
    bankedPoints: (score: number) =>
      `Banked ${score} points! Roll again or end turn.`,
    landslide: `What a landslide! Keep rolling...`,
    turnOver: (score: number) => `Turn over! You scored ${score} points!`,
    rerollsRemaining: (count: number) =>
      `Re-rolled! ${count} re-roll(s) remaining.`,
    fizzleNoScore: "💀 FIZZLE! No scoring dice! Use a re-roll if available.",
    fizzleStillFizzled: (count: number) =>
      `💀 FIZZLE! Still fizzled! Use a re-roll if available (${count} Extra Dice left).`,
    gameOver: (score: number) => `💀 FIZZLE! Game Over! Final score: ${score}`,
    fizzleContinue: (score: number) =>
      `💀 FIZZLE! Lost turn points, but you can continue! Total: ${score}`,
    autoRerollSaved: "🔄 Auto Re-roll used! Saved!",
    autoRerollFailed: "🔄 Auto Re-roll used! Still fizzled! 💀",
    upgradeApplied: "Upgrade applied!",
    bonusRerollAdded: "Bonus re-roll added!",
    guhkleTriggered: "😲 GUHKLE! First roll fizzle! Auto re-rolling...",
    guhkleSaved: "😅 GUHKLE! Scored on re-roll!",
    guhkleFailed: "💀 DOUBLE GUHKLE! Still fizzled!",
    certificationNeeded: (value: string | number) =>
      `Set of ${value} needs certification! Roll and score to clear.`,
    certificationIgnored: "Ignored matching dice! Re-rolling...",
  },
  errors: {
    selectDice: "Select some dice first!",
    notScoring: "Selected dice do not score!",
    bankFirst: "Bank your selected dice first!",
    mustBank: "You must bank some points before ending your turn!",
    thresholdNotMet: (threshold: number, current: number) =>
      `Need total score of ${threshold} to end turn. You have ${current}. Keep rolling!`,
    noRerolls: "No re-rolls available!",
    noExtraDice: "No extra dice available!",
    boardFull: "Board is already full!",
    certificationActive: "You must certify your set first!",
  },
  rules: {
    header: "Cosmic Wimpout Rules",
    scoringHeader: "Scoring Rules",
    shortcutsHeader: "Keyboard Shortcuts",
    one: "1 (10 pts)",
    five: "5 (5 pts)",
    threeOfKind: "Set (3 of a kind)",
    threeOfKindScore: "n×10 (111=100)",
    fourOfKind: "N/A",
    fiveOfKind: "Heap (5 of a kind)",
    sixOfKind: "N/A",
    straight: "N/A",
    threePairs: "N/A",
  },
  ui: {
    turn: "Turn",
    nextLevel: (turn: number) => `Turn ${turn}`,
    rerolls: "Re-Rolls",
    extraDice: "Extra Dice",
    highScore: "High Score",
    limit: "Limit",
    nextLimit: (score: number) => `Next Limit: ${score}`,
    totalScore: "Total",
    bankedScore: "Banked",
    stagedScore: "Staged",
    rules: "Rules",
    backToGame: "Back to Game",
    playGame: "PLAY GAME",
    upgrades: "Upgrades",
    dieUpgrades: "Die Upgrades",
    chooseUpgrade: "Choose an Upgrade",
    position: (pos: number) => `Position ${pos}`,
    none: "None",
    roll: "Roll",
    rollTooltip: "Roll dice (Space)",
    reroll: "Re-Roll",
    rerollTooltip: "Re-roll unscored dice (R)",
    endTurn: "End Turn",
    endTurnTooltip: "End turn (Enter)",
    newGame: "New Game",
    newGameTooltip: "New game (Backspace)",
  },
  upgrades: {
    descriptions: {
      bankedMultiplier: "2x total turn score when this die is banked",
      bankedBonus: "+500 total turn score when this die is banked",
      autoReroll:
        "Automatically re-rolls this die if it causes a Fizzle (3 uses)",
      setBonus:
        "Increases score by N^3 where N is number of Set Bonus dice in the scoring set",
      extraDie: "Immediately gain +1 Extra Die",
    },
    labels: {
      bankedMultiplier: "2x Banked",
      bankedBonus: "+500 Banked",
      autoReroll: "Auto Reroll",
      setBonus: "Set Bonus",
      extraDie: "Extra Die",
    },
  },
};
